---
version: "3.8"
services:
  movies:
    image: ajaychekurthy/paytmmoviesrepo:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: ajaychekurthy/paytmtrainrepo:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: ajaychekurthy/paytmrechargerepo:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: ajaychekurthy/paytmdthrepo:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
